from log import *

print(1)

logging.error(1)